### ISSUE TITLE
Client Docs ?  + License Changed

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-socket-client-python#2]
Hi there,
this is by far the easiest client to use
really enjoying your work 

I am getting 
```
✖ License issue: Expected 1576 but this account is 2000
```
my original license is of the [now deprecated] python automate, please advise on how to reissue me a new license pls :)

But mostly, where do i see the docs for the python client?
the best i got so far is to check the api-docs which upto now mapped the http request correctly with the client
but would love to see where all these functions are coming from and what parameters they expect 
![image](https://user-images.githubusercontent.com/9356048/172856901-9507e470-2811-46ef-a327-194f28c96f40.png)

Thanks a lot! :heart:

**Comment by mrodal** [comment]
You can ask @smashah on the [open-wa discord](https://discord.gg/dnpp72a) to change your license to your new phone number

Also, here's the docs for the nodejs api client, which this library uses: https://docs.openwa.dev/classes/api_Client.Client.html

**Comment by fire17** [comment]
### https://docs.openwa.dev/classes/api_Client.Client.html#sendLinkWithAutoPreview FTW!
![image](https://user-images.githubusercontent.com/9356048/172874514-02096503-c74a-4432-893d-292395205aea.png)

thanks @mrodal :heart:
