### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by yiftachn** [open-wa/wa-automate-socket-client-python#3]
Hey! do you have any python docs? could not find them if they exist.. 

Thanks!

**Comment by mrodal** [comment]
Hey! the docs are in the readme. For documentation on the underlying nodejs library and available methods you can check https://openwa.dev/docs/api/classes/api_Client.Client

**Comment by llinguini** [comment]
Hi! Linck down :( do you have any python docs?

**Comment by mrodal** [comment]
Sadly, the openwa project is discontinuated: 
https://smashah.gumroad.com/p/i-am-sorry-4d885edc-760a-46a4-aa24-83b41406b12f
