### ISSUE TITLE
Erorr while trying to send video

### ISSUE THREAD

**Issue by MhankBarBar** [open-wa/wa-automate-socket-client-python#6]
this is my code to trying send video from url

```bash
curl -X 'POST' \
  'http://localhost:8085/sendFileFromUrl' \
  -H 'accept: */*' \
  -H 'api_key: key' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {
    "to": "xxxx@c.us",
    "url": "https://example.com/file.mp4",
    "filename": "video.mp4"
  }
}'
```

this is the error code
```json
{
  "success": false,
  "error": {
    "name": "Error",
    "message": "Please set arguments in request json body, not in params. Evaluation failed: Error: InvalidMediaFileType\n    at h.sendToChat (https://web.whatsapp.com/app.a8429b8147f1b90a2f71.js:72:764642)\n    at pptr://__puppeteer_evaluation_script__:1:214142\n    at async window.<computed>.<computed> [as sendImage] (pptr://__puppeteer_evaluation_script__:1:210399)"
  }
}
```

thanks

**Comment by mrodal** [comment]
The error says InvalidMediaFileType
have you tried a different video? could you provide a video sample that gives you this error?

**Comment by MhankBarBar** [comment]
ive been trying to send different video but same

**Comment by MhankBarBar** [comment]
this is video im trying to send https://www.tikwm.com/video/media/hdplay/7190309970573921538.mp4

**Comment by mrodal** [comment]
Could you try video smaller than 16MB? Whatsapp has a 16MB limit on media

**Comment by MhankBarBar** [comment]
still error even though using a file with a size below 16MB, this is the file url for smaller size https://download.samplelib.com/mp4/sample-5s.mp4

**Comment by mrodal** [comment]
I have no problem sending that video. Which error are you getting and what version of openwa are you running?

**Comment by MhankBarBar** [comment]
4.55.0

**Comment by mrodal** [comment]
please share the exact curl call you are using without the phone number. And the response you get

**Comment by MhankBarBar** [comment]
> this is my code to trying send video from url
> 
> ```shell
> curl -X 'POST' \
>   'http://localhost:8085/sendFileFromUrl' \
>   -H 'accept: */*' \
>   -H 'api_key: key' \
>   -H 'Content-Type: application/json' \
>   -d '{
>   "args": {
>     "to": "xxxx@c.us",
>     "url": "https://example.com/file.mp4",
>     "filename": "video.mp4"
>   }
> }'
> ```
> 
> this is the error code
> 
> ```json
> {
>   "success": false,
>   "error": {
>     "name": "Error",
>     "message": "Please set arguments in request json body, not in params. Evaluation failed: Error: InvalidMediaFileType\n    at h.sendToChat (https://web.whatsapp.com/app.a8429b8147f1b90a2f71.js:72:764642)\n    at pptr://__puppeteer_evaluation_script__:1:214142\n    at async window.<computed>.<computed> [as sendImage] (pptr://__puppeteer_evaluation_script__:1:210399)"
>   }
> }
> ```
> 
> thanks

this is my curl code

**Comment by MhankBarBar** [comment]
i'm using python btw, cuz error im trying to call with curl using api explorer

**Comment by mrodal** [comment]
that is not the exact curl call, it has a wrong video url

**Comment by MhankBarBar** [comment]
```BASH
curl -X 'POST' \
  'http://localhost:8085/sendFileFromUrl' \
  -H 'accept: */*' \
  -H 'api_key: j0yd4z0' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {
    "url": "https://download.samplelib.com/mp4/sample-5s.mp4",
    "filename": "video.mp4"
  }
}'
```

like this?

**Comment by mrodal** [comment]
Yes, with that and the number I can send the video successfully. Im running 4.55.3 but I dont think that could be the issue. Could you share a screenshot with the call and the response?

**Comment by MhankBarBar** [comment]
![image](https://user-images.githubusercontent.com/55822959/213872383-11681e2b-db7e-43c0-b52b-175dd5174dfd.png)

**Comment by mrodal** [comment]
how are you running openwa? docker? Could you share the run command?

**Comment by MhankBarBar** [comment]
npx @open-wa/wa-automate --socket -p 8085 -k key

**Comment by mrodal** [comment]
do you have docker installed? could you try with docker?
`docker run -p 8085:8085 openwa/wa-automate --socket -p 8085 -k key`

**Comment by MhankBarBar** [comment]
wait, I'll try with docker

**Comment by MhankBarBar** [comment]
yes, it worked when using docker

**Comment by MhankBarBar** [comment]
thanks for help and sorry for taking ur time

im closing this issue

**Comment by mrodal** [comment]
no worries, glad I could help

**Comment by smashah** [comment]
@mrodal @MhankBarBar in order to send video you need to use `--use-chrome` flag (because default chromium doesn't have access to ffmpeg). The reason it worked in the docker is because the docker image uses chrome by default.

**Comment by MhankBarBar** [comment]
ow, thanks for give that info @smashah

**Comment by smashah** [comment]
@MhankBarBar no worries please ping me on discord when you get the chance
